version: '3.9'

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
