version: '3.9'

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    volumes:
      - .:/app
    environment:
      - S3_URL=s3://holds-json-resources/msg.json




