version: 2.1

executors:
   app:
     machine:
       image: ubuntu-2004:202010-01
     working_directory: ~/repo

commands:
  installing-dependencies:
     description: "Installing nodejs 17.7.2"
     steps:
       - run:
            name: "Installing nodejs 17.7.2"
            working_directory: ~/repo
            command: | 
              sudo apt-get update 
              sudo apt-get install -y nodejs
              npm install


  restore-cache:
     description: "Restoring cache"
     steps:
        - restore_cache:
              keys:
                - app-{{ checksum "package.json" }}
                - app-
  save-cache:
     description: "Saving cache"
     steps:
        - save_cache:
              paths:
                - node_modules
              key: -app-{{ checksum "package.json" }}
               
   
  install-awscli-v2:
     description: "Install AWS CLI v2"
     steps:
       - run:
            name: "Installing AWS CLI v2"
            working_directory: ~/repo
            command: |
               sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
               sudo unzip awscliv2.zip
               sudo ./aws/install
               sudo rm -rf awscliv2.zip
               sudo rm -rf aws
               aws --version 

  login-aws-erc:
      description: "Login to AWS ECR"
      steps:
        - run:
              name: "Login to AWS ECR"
              working_directory: ~/repo
              command: |
                  aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/f6d3m9u4
   
  docker-build-image:
        description: "Build Docker Image and push to ECR"
        steps:
          - run:
              name: "Building Docker Image and pushing to ECR"
              working_directory: ~/repo
              command: |
                docker build -t erc-test-repo .
                docker tag erc-test-repo:latest public.ecr.aws/f6d3m9u4/erc-test-repo:latest
                docker push public.ecr.aws/f6d3m9u4/erc-test-repo:latest
                echo "Docker Image pushed to ECR"
                
jobs:
  push-to-aws-ecr:
     executor: app
     steps:
       - checkout
       - install-awscli-v2
       - login-aws-erc
       - restore-cache
       - save-cache
workflows:
  push-container-to-ecr:
    jobs:
      - push-to-aws-ecr
   
    

      
     
         
        

