version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.0.0
  # https://circleci.com/developer/orbs/orb/circleci/aws-ecr
  aws-ecr: circleci/aws-ecr@7.3.0
jobs:
  test:
    executor:
      name: node/default
      tag: 16.10.0
    steps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
    - run:
        command: npm test
        name: Jest tests
workflows:
  node-tests:
    jobs:
    - test
    # Envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, AWS_ECR_ACCOUNT_URL
    - aws-ecr/build-and-push-image:
        repo: ${AWS_RESOURCE_NAME_PREFIX}
        tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
        dockerfile: Dockerfile
        path: .
        requires:
          - test
