version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install -y python3-pip
            sudo pip3 install awscli --upgrade
      - run:
          name: installing docker
          command: |
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce
            docker version
      - run:
          name: installing docker-compose
          command: |
            sudo mkdir -p ~/.docker/cli-plugins/
            sudo curl -SL https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
            sudo chmod +x ~/.docker/cli-plugins/docker-compose
            sudo chown -R $USER ~/.docker/cli-plugins/docker-compose
      - run:
          name: checking docker compose version
          command: |
            docker-compose --version
      - run:
          name: loging into erc
          command: |
            $(aws ecr get-login --no-include-email --region us-east-1)
      - run:
          name: build docker image
          command: |
            docker build -t $AWS_RESOURCE_NAME_PREFIX .
      - run:
          name: tagging docker image
          command: |
            docker tag $AWS_RESOURCE_NAME_PREFIX:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$AWS_RESOURCE_NAME_PREFIX:latest
      - run: 
          name: push docker image to ECR
          command: |
            docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$AWS_RESOURCE_NAME_PREFIX:latest


workflows:
   version: 2.1
   execute_bulk:
      jobs:
        - build
   
         
        

